name: JMH Benchmarks

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build fat JMH jar
        run: mvn clean package -DskipTests


  throughput:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download JMH jar
        uses: actions/download-artifact@v3
        with:
          name: jmh-jar

      - name: Run throughput benchmark
        run: |
          java -jar jmh-lab-1.0-SNAPSHOT.jar \
            com.xinchentechnote.SpscBenchmark \
            -f 1 -wi 3 -i 5 \
            -t 2 \
            -bm Throughput \
            -rff spsc_thrput.json

      - name: Upload throughput result
        uses: actions/upload-artifact@v3
        with:
          name: spsc-throughput
          path: spsc_thrput.json

  latency:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download JMH jar
        uses: actions/download-artifact@v3
        with:
          name: jmh-jar

      - name: Run latency benchmark
        run: |
          java -jar jmh-lab-1.0-SNAPSHOT.jar \
            com.xinchentechnote.SpscBenchmark \
            -f 1 -wi 3 -i 5 \
            -t 2 \
            -bm AverageTime \
            -rff spsc_lat.json
