name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 Java 环境（可根据需要选择 Java 8/11/17）
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # 构建 & 测试
      - name: Build with Maven
        run: mvn -B clean verify

      # （可选）发布到 Sonatype/Maven Central、上传代码覆盖率报告等
