name: JMH Benchmarks

on:
  workflow_dispatch:
    inputs:
      benchmark-class:
        description: 'Select benchmark class to run'
        required: true
        default: 'StringConcatBenchmark'
        type: choice
        options:
          - MemeryVisibilityBenchmark
          - StringConcatBenchmark

jobs:
  throughput:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - run: mvn clean package -DskipTests

      - name: Run Throughput Benchmark
        run: |
          java -jar target/jmh-lab-1.0-SNAPSHOT.jar \
            com.xinchentechnote.${{ github.event.inputs.benchmark-class || 'StringConcatBenchmark' }} \
            -bm Throughput -f 1 -wi 3 -i 5 -t 1 \
            -rff result_thrput.json

  latency:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - run: mvn clean package -DskipTests

      - name: Run Latency Benchmark
        run: |
          java -jar target/jmh-lab-1.0-SNAPSHOT.jar \
            com.xinchentechnote.${{ github.event.inputs.benchmark-class || 'StringConcatBenchmark' }} \
            -bm AverageTime -f 1 -wi 3 -i 5 -t 1 \
            -rff result_lat.json