name: JMH Benchmarks

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      jar-path: ${{ steps.package.outputs.jar }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build fat JMH jar
        id: package
        run: |
          mvn clean package -DskipTests
          echo "jar=target/jmh-lab-1.0-SNAPSHOT.jar" >> $GITHUB_OUTPUT

  throughput:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build and run throughput
        run: |
          mvn clean package -DskipTests
          java -jar target/jmh-lab-1.0-SNAPSHOT.jar \
            com.xinchentechnote.SpscBenchmark \
            -f 1 -wi 3 -i 5 \
            -t 2 \
            -bm Throughput \
            -rff spsc_thrput.json

  latency:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build and run latency
        run: |
          mvn clean package -DskipTests
          java -jar target/jmh-lab-1.0-SNAPSHOT.jar \
            com.xinchentechnote.SpscBenchmark \
            -f 1 -wi 3 -i 5 \
            -t 2 \
            -bm AverageTime \
            -rff spsc_lat.json
