name: JMH Benchmarks

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build fat JMH jar
        run: mvn clean package -DskipTests

      - name: Run throughput benchmark
        run: |
          java -jar target/jmh-lab-1.0-SNAPSHOT.jar \
            com.xinchentechnote.SpscBenchmark \
            -f 3 -wi 5 -i 10 \
            -t 2 \
            -bm Throughput \
            -rff spsc_thrput.json

      - name: Run latency benchmark
        run: |
          java -jar target/jmh-lab-1.0-SNAPSHOT.jar \
            com.xinchentechnote.SpscBenchmark \
            -f 3 -wi 5 -i 10 \
            -t 2 \
            -bm AverageTime \
            -rff spsc_lat.json
