name: JMH Benchmarks

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  throughput:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - run: mvn clean package -DskipTests

      - run: |
          java -jar target/jmh-lab-1.0-SNAPSHOT.jar \
            com.xinchentechnote.StringConcatBenchmark \
            -bm Throughput -f 1 -wi 3 -i 5 -t 1 \
            -rff result_thrput.json

  latency:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - run: mvn clean package -DskipTests

      - run: |
          java -jar target/jmh-lab-1.0-SNAPSHOT.jar \
            com.xinchentechnote.StringConcatBenchmark \
            -bm AverageTime -f 1 -wi 3 -i 5 -t 1 \
            -rff result_lat.json
